// <auto-generated />
using JJ.INFRASTRUCTURE.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JJ.INFRASTRUCTURE.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250607193036_primeiraMigration")]
    partial class primeiraMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JJ.DOMAIN.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "https://placehold.co/300x200/3b82f6/white?text=Notebook+SQL",
                            Name = "Notebook Gamer X",
                            Price = 7499.90m
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "https://placehold.co/300x200/ef4444/white?text=Mouse+SQL",
                            Name = "Mouse Pro Gamer",
                            Price = 129.50m
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "https://placehold.co/300x200/22c55e/white?text=Teclado+SQL",
                            Name = "Teclado Mecânico Avançado",
                            Price = 499.00m
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "https://placehold.co/300x200/6366f1/white?text=Monitor+SQL",
                            Name = "Monitor UltraWide 34\"",
                            Price = 2899.99m
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "https://placehold.co/300x200/ec4899/white?text=Headset+SQL",
                            Name = "Headset Gamer Imersivo",
                            Price = 350.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
